from typing import Protocol
from uuid import UUID
from serdial21.modules.privacy.domain.entities import DataSubjectRequest, LegalHold, RetentionPolicy

class PrivacyRepository(Protocol):
    def add_policy(self, policy: RetentionPolicy) -> None: ...
    def policy(self, tenant_id: UUID, category: str) -> RetentionPolicy | None: ...
    def add_hold(self, hold: LegalHold) -> None: ...
    def active_hold(self, tenant_id: UUID, company_id: UUID | None, resource_type: str, resource_id: UUID) -> LegalHold | None: ...
    def get_hold(self, tenant_id: UUID, hold_id: UUID) -> LegalHold | None: ...
    def save_hold(self, hold: LegalHold) -> None: ...
    def add_dsr(self, request: DataSubjectRequest) -> None: ...
    def get_dsr(self, tenant_id: UUID, request_id: UUID) -> DataSubjectRequest | None: ...
    def save_dsr(self, request: DataSubjectRequest) -> None: ...
