'''document_evidence_foundation

Revision ID: 20260904_0004
Revises: 20260904_0003
Create Date: 2026-09-04 09:32:43.073667
'''

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import serdial21.bootstrap.database



revision: str = '20260904_0004'
down_revision: str | Sequence[str] | None = '20260904_0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('captured_at', serdial21.bootstrap.database.UTCDateTime(), nullable=False),
    sa.Column('verified_at', serdial21.bootstrap.database.UTCDateTime(), nullable=False),
    sa.Column('created_at', serdial21.bootstrap.database.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_evidence_artifacts_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_artifacts')),
    sa.UniqueConstraint('tenant_id', 'hash_algorithm', 'content_hash', name='uq_evidence_artifacts_tenant_hash'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_evidence_artifacts_tenant_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('received_items', sa.Integer(), nullable=False),
    sa.Column('duplicate_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('started_at', serdial21.bootstrap.database.UTCDateTime(), nullable=False),
    sa.Column('completed_at', serdial21.bootstrap.database.UTCDateTime(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', serdial21.bootstrap.database.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id'], ['companies.tenant_id', 'companies.id'], name='fk_import_batches_tenant_company'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches')),
    sa.UniqueConstraint('tenant_id', 'company_id', 'id', name='uq_import_batches_scope_id'),
    sa.UniqueConstraint('tenant_id', 'company_id', 'source', 'idempotency_key', name='uq_import_batches_scope_idempotency'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('ix_import_batches_scope_status', 'import_batches', ['tenant_id', 'company_id', 'status'], unique=False)
    op.create_table('transformation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('previous_run_id', sa.Uuid(), nullable=True),
    sa.Column('parser_name', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=100), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', serdial21.bootstrap.database.UTCDateTime(), nullable=False),
    sa.Column('completed_at', serdial21.bootstrap.database.UTCDateTime(), nullable=True),
    sa.Column('created_at', serdial21.bootstrap.database.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'artifact_id'], ['evidence_artifacts.tenant_id', 'evidence_artifacts.id'], name='fk_transformation_runs_tenant_artifact'),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id', 'previous_run_id'], ['transformation_runs.tenant_id', 'transformation_runs.company_id', 'transformation_runs.id'], name='fk_transformation_runs_previous'),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id'], ['companies.tenant_id', 'companies.id'], name='fk_transformation_runs_tenant_company'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transformation_runs')),
    sa.UniqueConstraint('tenant_id', 'company_id', 'id', name='uq_transformation_runs_scope_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('ix_transformation_runs_scope_status', 'transformation_runs', ['tenant_id', 'company_id', 'status'], unique=False)
    op.create_table('artifact_receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('external_key', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('received_at', serdial21.bootstrap.database.UTCDateTime(), nullable=False),
    sa.Column('created_at', serdial21.bootstrap.database.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'artifact_id'], ['evidence_artifacts.tenant_id', 'evidence_artifacts.id'], name='fk_artifact_receipts_tenant_artifact'),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id', 'batch_id'], ['import_batches.tenant_id', 'import_batches.company_id', 'import_batches.id'], name='fk_artifact_receipts_scope_batch'),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id'], ['companies.tenant_id', 'companies.id'], name='fk_artifact_receipts_tenant_company'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact_receipts')),
    sa.UniqueConstraint('tenant_id', 'company_id', 'id', name='uq_artifact_receipts_scope_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('ix_artifact_receipts_scope_time', 'artifact_receipts', ['tenant_id', 'company_id', 'received_at'], unique=False)
    op.create_table('lineage_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source_version', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('target_version', sa.Integer(), nullable=True),
    sa.Column('transformation_run_id', sa.Uuid(), nullable=True),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('created_at', serdial21.bootstrap.database.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id', 'transformation_run_id'], ['transformation_runs.tenant_id', 'transformation_runs.company_id', 'transformation_runs.id'], name='fk_lineage_edges_scope_run'),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id'], ['companies.tenant_id', 'companies.id'], name='fk_lineage_edges_tenant_company'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lineage_edges')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('ix_lineage_edges_source', 'lineage_edges', ['tenant_id', 'company_id', 'source_type', 'source_id'], unique=False)
    op.create_index('ix_lineage_edges_target', 'lineage_edges', ['tenant_id', 'company_id', 'target_type', 'target_id'], unique=False)
    op.create_table('validation_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('transformation_run_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('field_path', sa.String(length=500), nullable=True),
    sa.Column('rule_reference', sa.String(length=255), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('resolution_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', serdial21.bootstrap.database.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id', 'transformation_run_id'], ['transformation_runs.tenant_id', 'transformation_runs.company_id', 'transformation_runs.id'], name='fk_validation_issues_scope_run'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_issues')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('ix_validation_issues_scope_severity', 'validation_issues', ['tenant_id', 'company_id', 'severity'], unique=False)
    op.create_table('import_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_subject_type', sa.String(length=100), nullable=True),
    sa.Column('created_subject_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', serdial21.bootstrap.database.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id', 'batch_id'], ['import_batches.tenant_id', 'import_batches.company_id', 'import_batches.id'], name='fk_import_items_scope_batch'),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id', 'receipt_id'], ['artifact_receipts.tenant_id', 'artifact_receipts.company_id', 'artifact_receipts.id'], name='fk_import_items_scope_receipt'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_items')),
    sa.UniqueConstraint('tenant_id', 'company_id', 'batch_id', 'sequence', name='uq_import_items_batch_sequence'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('ix_import_items_scope_status', 'import_items', ['tenant_id', 'company_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_import_items_scope_status', table_name='import_items')
    op.drop_table('import_items')
    op.drop_index('ix_validation_issues_scope_severity', table_name='validation_issues')
    op.drop_table('validation_issues')
    op.drop_index('ix_lineage_edges_target', table_name='lineage_edges')
    op.drop_index('ix_lineage_edges_source', table_name='lineage_edges')
    op.drop_table('lineage_edges')
    op.drop_index('ix_artifact_receipts_scope_time', table_name='artifact_receipts')
    op.drop_table('artifact_receipts')
    op.drop_index('ix_transformation_runs_scope_status', table_name='transformation_runs')
    op.drop_table('transformation_runs')
    op.drop_index('ix_import_batches_scope_status', table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_table('evidence_artifacts')
    # ### end Alembic commands ###
