'''Persistência da jornada NF-e para intenção Domínio bloqueada antes de homologação.'''
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa
import serdial21.bootstrap.database

revision: str = '20260906_0007'
down_revision: str | Sequence[str] | None = '20260905_0006'
branch_labels = depends_on = None
UTC = serdial21.bootstrap.database.UTCDateTime

def _scope(columns: list[sa.Column[object]], table: str) -> list[object]:
 return columns + [sa.ForeignKeyConstraint(['tenant_id','company_id'],['companies.tenant_id','companies.id']),sa.UniqueConstraint('tenant_id','company_id','id',name=f'uq_{table}_scope_id'),{'mysql_charset':'utf8mb4'}]

def upgrade() -> None:
 op.create_table('workflow_cases',*_scope([sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('tenant_id',sa.Uuid(),nullable=False),sa.Column('company_id',sa.Uuid(),nullable=False),sa.Column('subject_type',sa.String(100),nullable=False),sa.Column('subject_id',sa.Uuid(),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('correlation_id',sa.Uuid(),nullable=False),sa.Column('created_at',UTC(),nullable=False,server_default=sa.text('(CURRENT_TIMESTAMP)'))],'workflow_cases'))
 op.create_table('workflow_work_items',*_scope([sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('tenant_id',sa.Uuid(),nullable=False),sa.Column('company_id',sa.Uuid(),nullable=False),sa.Column('workflow_case_id',sa.Uuid(),nullable=False),sa.Column('subject_type',sa.String(100),nullable=False),sa.Column('subject_id',sa.Uuid(),nullable=False),sa.Column('work_type',sa.String(64),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('priority',sa.String(32),nullable=False),sa.Column('assigned_to_membership_id',sa.Uuid()),sa.Column('due_at',UTC()),sa.Column('created_at',UTC(),nullable=False,server_default=sa.text('(CURRENT_TIMESTAMP)')),sa.Column('completed_at',UTC()),sa.Column('correlation_id',sa.Uuid(),nullable=False),sa.ForeignKeyConstraint(['tenant_id','company_id','workflow_case_id'],['workflow_cases.tenant_id','workflow_cases.company_id','workflow_cases.id'])],'workflow_work_items'))
 op.create_table('workflow_approval_requests',*_scope([sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('tenant_id',sa.Uuid(),nullable=False),sa.Column('company_id',sa.Uuid(),nullable=False),sa.Column('workflow_case_id',sa.Uuid(),nullable=False),sa.Column('proposal_revision_id',sa.Uuid()),sa.Column('proposal_revision_hash',sa.String(64)),sa.Column('status',sa.String(32),nullable=False),sa.Column('requested_role',sa.String(32),nullable=False),sa.Column('correlation_id',sa.Uuid(),nullable=False),sa.Column('created_at',UTC(),nullable=False,server_default=sa.text('(CURRENT_TIMESTAMP)')),sa.ForeignKeyConstraint(['tenant_id','company_id','workflow_case_id'],['workflow_cases.tenant_id','workflow_cases.company_id','workflow_cases.id'])],'workflow_approval_requests'))
 op.create_table('authorized_effects',*_scope([sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('tenant_id',sa.Uuid(),nullable=False),sa.Column('company_id',sa.Uuid(),nullable=False),sa.Column('workflow_case_id',sa.Uuid(),nullable=False),sa.Column('approval_request_id',sa.Uuid(),nullable=False),sa.Column('subject_type',sa.String(100),nullable=False),sa.Column('subject_id',sa.Uuid(),nullable=False),sa.Column('effect_type',sa.String(64),nullable=False),sa.Column('requested_payload',sa.JSON(),nullable=False),sa.Column('authorized_payload',sa.JSON()),sa.Column('authorization_status',sa.String(32),nullable=False),sa.Column('authorized_by_membership_id',sa.Uuid()),sa.Column('authorized_at',UTC()),sa.Column('executed_at',UTC()),sa.Column('execution_status',sa.String(32),nullable=False),sa.Column('correlation_id',sa.Uuid(),nullable=False),sa.Column('created_at',UTC(),nullable=False,server_default=sa.text('(CURRENT_TIMESTAMP)')),sa.ForeignKeyConstraint(['tenant_id','company_id','workflow_case_id'],['workflow_cases.tenant_id','workflow_cases.company_id','workflow_cases.id']),sa.ForeignKeyConstraint(['tenant_id','company_id','approval_request_id'],['workflow_approval_requests.tenant_id','workflow_approval_requests.company_id','workflow_approval_requests.id'])],'authorized_effects'))
 op.create_table('pre_homologation_export_batches',*_scope([sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('tenant_id',sa.Uuid(),nullable=False),sa.Column('company_id',sa.Uuid(),nullable=False),sa.Column('authorized_effect_id',sa.Uuid(),nullable=False),sa.Column('fiscal_document_id',sa.Uuid(),nullable=False),sa.Column('canonical_record_id',sa.Uuid(),nullable=False),sa.Column('artifact_id',sa.Uuid(),nullable=False),sa.Column('connector_name',sa.String(64),nullable=False),sa.Column('status',sa.String(64),nullable=False),sa.Column('block_reasons',sa.JSON(),nullable=False),sa.Column('correlation_id',sa.Uuid(),nullable=False),sa.Column('created_at',UTC(),nullable=False,server_default=sa.text('(CURRENT_TIMESTAMP)')),sa.ForeignKeyConstraint(['tenant_id','company_id','authorized_effect_id'],['authorized_effects.tenant_id','authorized_effects.company_id','authorized_effects.id']),sa.ForeignKeyConstraint(['tenant_id','company_id','fiscal_document_id'],['fiscal_documents.tenant_id','fiscal_documents.company_id','fiscal_documents.id']),sa.ForeignKeyConstraint(['tenant_id','company_id','canonical_record_id'],['canonical_records.tenant_id','canonical_records.company_id','canonical_records.id']),sa.ForeignKeyConstraint(['tenant_id','artifact_id'],['evidence_artifacts.tenant_id','evidence_artifacts.id'])],'pre_homologation_export_batches'))
 op.create_index('ix_workflow_work_items_scope_status','workflow_work_items',['tenant_id','company_id','status'])
 op.create_index('ix_pre_homologation_export_batches_correlation','pre_homologation_export_batches',['tenant_id','correlation_id'])

def downgrade() -> None:
 op.drop_index('ix_pre_homologation_export_batches_correlation',table_name='pre_homologation_export_batches');op.drop_index('ix_workflow_work_items_scope_status',table_name='workflow_work_items');op.drop_table('pre_homologation_export_batches');op.drop_table('authorized_effects');op.drop_table('workflow_approval_requests');op.drop_table('workflow_work_items');op.drop_table('workflow_cases')
