'''Schema OFX banc\u00e1rio; entidades derivadas e imut\u00e1veis.''' 
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa
import serdial21.bootstrap.database
revision: str = '20260905_0006'
down_revision: str | Sequence[str] | None = '20260904_0005'
branch_labels = depends_on = None
UTC = serdial21.bootstrap.database.UTCDateTime
def upgrade() -> None:
 op.create_table('bank_accounts',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('tenant_id',sa.Uuid(),nullable=False),sa.Column('company_id',sa.Uuid(),nullable=False),sa.Column('bank_id',sa.String(40)),sa.Column('branch_id',sa.String(40)),sa.Column('account_number',sa.String(100),nullable=False),sa.Column('account_type',sa.String(30)),sa.Column('currency_code',sa.String(10)),sa.Column('external_identity',sa.String(255),nullable=False),sa.Column('created_at',UTC(),nullable=False,server_default=sa.text('(CURRENT_TIMESTAMP)')),sa.ForeignKeyConstraint(['tenant_id','company_id'],['companies.tenant_id','companies.id']),sa.UniqueConstraint('tenant_id','company_id','external_identity',name='uq_bank_accounts_scope_identity'),sa.UniqueConstraint('tenant_id','company_id','id',name='uq_bank_accounts_scope_id'),mysql_charset='utf8mb4')
 op.create_table('bank_statements',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('tenant_id',sa.Uuid(),nullable=False),sa.Column('company_id',sa.Uuid(),nullable=False),sa.Column('bank_account_id',sa.Uuid(),nullable=False),sa.Column('artifact_id',sa.Uuid(),nullable=False),sa.Column('transformation_run_id',sa.Uuid(),nullable=False),sa.Column('schema_version',sa.String(30),nullable=False),sa.Column('start_date',sa.Date()),sa.Column('end_date',sa.Date()),sa.Column('opening_balance',sa.Numeric(20,2)),sa.Column('closing_balance',sa.Numeric(20,2)),sa.Column('currency_code',sa.String(10)),sa.Column('sign_policy',sa.String(80),nullable=False),sa.Column('source_hash',sa.String(64),nullable=False),sa.Column('fingerprint',sa.String(64),nullable=False),sa.Column('created_at',UTC(),nullable=False,server_default=sa.text('(CURRENT_TIMESTAMP)')),sa.ForeignKeyConstraint(['tenant_id','company_id','bank_account_id'],['bank_accounts.tenant_id','bank_accounts.company_id','bank_accounts.id']),sa.ForeignKeyConstraint(['tenant_id','artifact_id'],['evidence_artifacts.tenant_id','evidence_artifacts.id']),sa.ForeignKeyConstraint(['tenant_id','company_id','artifact_id','transformation_run_id'],['transformation_runs.tenant_id','transformation_runs.company_id','transformation_runs.artifact_id','transformation_runs.id']),sa.UniqueConstraint('tenant_id','company_id','id',name='uq_bank_statements_scope_id'),sa.UniqueConstraint('tenant_id','company_id','bank_account_id','artifact_id',name='uq_bank_statements_scope_account_artifact'),mysql_charset='utf8mb4')
 op.create_table('bank_transactions',sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('tenant_id',sa.Uuid(),nullable=False),sa.Column('company_id',sa.Uuid(),nullable=False),sa.Column('bank_statement_id',sa.Uuid(),nullable=False),sa.Column('bank_account_id',sa.Uuid(),nullable=False),sa.Column('fitid',sa.String(255)),sa.Column('external_reference',sa.String(255)),sa.Column('transaction_date',sa.Date()),sa.Column('posted_date',sa.Date()),sa.Column('amount',sa.Numeric(20,2),nullable=False),sa.Column('direction',sa.String(10),nullable=False),sa.Column('description',sa.String(1000)),sa.Column('document_number',sa.String(255)),sa.Column('fingerprint',sa.String(64),nullable=False),sa.Column('identity_kind',sa.String(20),nullable=False),sa.Column('created_at',UTC(),nullable=False,server_default=sa.text('(CURRENT_TIMESTAMP)')),sa.ForeignKeyConstraint(['tenant_id','company_id','bank_statement_id'],['bank_statements.tenant_id','bank_statements.company_id','bank_statements.id']),sa.ForeignKeyConstraint(['tenant_id','company_id','bank_account_id'],['bank_accounts.tenant_id','bank_accounts.company_id','bank_accounts.id']),sa.UniqueConstraint('tenant_id','company_id','id',name='uq_bank_transactions_scope_id'),sa.UniqueConstraint('tenant_id','company_id','bank_account_id','fitid',name='uq_bank_transactions_scope_fitid'),sa.UniqueConstraint('tenant_id','company_id','bank_account_id','fingerprint',name='uq_bank_transactions_scope_fingerprint'),mysql_charset='utf8mb4')
 op.create_index('ix_bank_transactions_scope_posted_date','bank_transactions',['tenant_id','company_id','posted_date'])
def downgrade() -> None:
 op.drop_index('ix_bank_transactions_scope_posted_date',table_name='bank_transactions');op.drop_table('bank_transactions');op.drop_table('bank_statements');op.drop_table('bank_accounts')
