'''nfe55_fiscal_documents

Revision ID: 20260904_0005
Revises: 20260904_0004
Create Date: 2026-09-04 10:01:40.470300
'''

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import serdial21.bootstrap.database



revision: str = '20260904_0005'
down_revision: str | Sequence[str] | None = '20260904_0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ux_transformation_runs_scope_artifact_id',
        'transformation_runs',
        ['tenant_id', 'company_id', 'artifact_id', 'id'],
        unique=True,
    )
    op.create_table('canonical_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('transformation_run_id', sa.Uuid(), nullable=False),
    sa.Column('record_type', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=100), nullable=False),
    sa.Column('external_identity', sa.String(length=100), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('fact_at', serdial21.bootstrap.database.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', serdial21.bootstrap.database.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'artifact_id'], ['evidence_artifacts.tenant_id', 'evidence_artifacts.id'], name='fk_canonical_records_tenant_artifact'),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id', 'artifact_id', 'transformation_run_id'], ['transformation_runs.tenant_id', 'transformation_runs.company_id', 'transformation_runs.artifact_id', 'transformation_runs.id'], name='fk_canonical_records_scope_run'),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id'], ['companies.tenant_id', 'companies.id'], name='fk_canonical_records_tenant_company'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_records')),
    sa.UniqueConstraint('tenant_id', 'company_id', 'id', name='uq_canonical_records_scope_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('ix_canonical_records_external_identity', 'canonical_records', ['tenant_id', 'company_id', 'record_type', 'external_identity'], unique=False)
    op.create_index('ux_canonical_records_scope_artifact_id', 'canonical_records', ['tenant_id', 'company_id', 'artifact_id', 'id'], unique=True)
    op.create_table('fiscal_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_record_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('access_key', sa.String(length=44), nullable=False),
    sa.Column('model', sa.String(length=2), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('document_number', sa.String(length=20), nullable=True),
    sa.Column('operation_nature', sa.String(length=255), nullable=True),
    sa.Column('issuer_tax_id', sa.String(length=32), nullable=True),
    sa.Column('issuer_name', sa.String(length=255), nullable=True),
    sa.Column('recipient_tax_id', sa.String(length=32), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('issued_at', serdial21.bootstrap.database.UTCDateTime(), nullable=True),
    sa.Column('movement_at', serdial21.bootstrap.database.UTCDateTime(), nullable=True),
    sa.Column('products_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('freight_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('insurance_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('invoice_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('observed_status', sa.String(length=32), nullable=False),
    sa.Column('protocol_status_code', sa.String(length=10), nullable=True),
    sa.Column('protocol_status_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', serdial21.bootstrap.database.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'artifact_id'], ['evidence_artifacts.tenant_id', 'evidence_artifacts.id'], name='fk_fiscal_documents_tenant_artifact'),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id', 'artifact_id', 'canonical_record_id'], ['canonical_records.tenant_id', 'canonical_records.company_id', 'canonical_records.artifact_id', 'canonical_records.id'], name='fk_fiscal_documents_scope_canonical'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscal_documents')),
    sa.UniqueConstraint('tenant_id', 'company_id', 'access_key', name='uq_fiscal_documents_scope_access_key'),
    sa.UniqueConstraint('tenant_id', 'company_id', 'canonical_record_id', name='uq_fiscal_documents_scope_canonical'),
    sa.UniqueConstraint('tenant_id', 'company_id', 'id', name='uq_fiscal_documents_scope_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('ix_fiscal_documents_issued_at', 'fiscal_documents', ['tenant_id', 'company_id', 'issued_at'], unique=False)
    op.create_table('fiscal_document_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('fiscal_document_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('ncm', sa.String(length=16), nullable=True),
    sa.Column('cfop', sa.String(length=8), nullable=True),
    sa.Column('commercial_unit', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit_value', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('gross_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('other_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('included_in_total', sa.Boolean(), nullable=True),
    sa.Column('created_at', serdial21.bootstrap.database.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id', 'fiscal_document_id'], ['fiscal_documents.tenant_id', 'fiscal_documents.company_id', 'fiscal_documents.id'], name='fk_fiscal_document_items_scope_document'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscal_document_items')),
    sa.UniqueConstraint('tenant_id', 'company_id', 'fiscal_document_id', 'sequence', name='uq_fiscal_document_items_scope_sequence'),
    sa.UniqueConstraint('tenant_id', 'company_id', 'id', name='uq_fiscal_document_items_scope_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('tax_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('fiscal_document_item_id', sa.Uuid(), nullable=False),
    sa.Column('tax_type', sa.String(length=20), nullable=False),
    sa.Column('tax_status', sa.String(length=10), nullable=True),
    sa.Column('calculation_base', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', serdial21.bootstrap.database.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'company_id', 'fiscal_document_item_id'], ['fiscal_document_items.tenant_id', 'fiscal_document_items.company_id', 'fiscal_document_items.id'], name='fk_tax_details_scope_item'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_details')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('ix_tax_details_scope_type', 'tax_details', ['tenant_id', 'company_id', 'tax_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tax_details_scope_type', table_name='tax_details')
    op.drop_table('tax_details')
    op.drop_table('fiscal_document_items')
    op.drop_index('ix_fiscal_documents_issued_at', table_name='fiscal_documents')
    op.drop_table('fiscal_documents')
    op.drop_index('ux_canonical_records_scope_artifact_id', table_name='canonical_records')
    op.drop_index('ix_canonical_records_external_identity', table_name='canonical_records')
    op.drop_table('canonical_records')
    op.drop_index('ux_transformation_runs_scope_artifact_id', table_name='transformation_runs')
    # ### end Alembic commands ###
