'use strict';
// Presentation-only synthetic data. No credentials, persistence or remote calls.
const records = [
  {id:'NF-e-001',name:'Compra de mercadorias',type:'fiscal',rule:'Regra demonstrativa F-01 · v1',proposal:'Proposta P-001',status:'review',owner:'Analista exemplo'},
  {id:'NF-e-002',name:'Venda de mercadorias',type:'fiscal',rule:'Regra demonstrativa F-02 · v1',proposal:'Proposta P-002',status:'review',owner:'Profissional exemplo'},
  {id:'OFX-003',name:'Tarifa bancária sintética',type:'financial',rule:'Regra demonstrativa B-01 · v1',proposal:'Proposta P-003',status:'review',owner:'Analista exemplo'},
  {id:'OFX-004',name:'Recebimento sintético',type:'financial',rule:'Regra demonstrativa B-02 · v1',proposal:'Proposta P-004',status:'approved',owner:'Profissional exemplo'},
  {id:'NF-e-005',name:'Documento em período bloqueado',type:'fiscal',rule:'Regra demonstrativa F-01 · v1',proposal:'Proposta P-005',status:'blocked',owner:'Profissional exemplo'},
  {id:'OFX-006',name:'Movimentação em processamento',type:'financial',rule:'Aguardando classificação',proposal:'Ainda não gerada',status:'processing',owner:'Não atribuído'}
];
const states = {review:['amber','◷ Revisão humana'],approved:['green','✓ Aprovado por profissional'],blocked:['red','⊘ Período bloqueado'],processing:['blue','◌ Processando']};
const modules = {overview:['Visão geral',''],portal:['Portal do Cliente','Prévia do recebimento centralizado. O portal externo ainda depende de integração e autorização.'],fiscal:['Inteligência Fiscal','Documentos fiscais sintéticos e suas propostas para conferência.'],financial:['Inteligência Financeira','Movimentações sintéticas, classificação e pendências de revisão.'],accounting:['Inteligência Contábil','Propostas preparadas para revisão. Nenhuma escrituração oficial é realizada aqui.'],governance:['Governança e Segurança','Acompanhe os bloqueios ilustrativos. A gestão de acesso e o histórico real dependem do backend autenticado.']};
let currentModule='overview';
const $ = selector => document.querySelector(selector);
function node(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
const metrics=[['Documentos recebidos','6','Neste conjunto sintético'],['Processados automaticamente','5','Preparação, não aprovação'],['Aguardando revisão','3','Conferência necessária'],['Exceções','1','Período bloqueado'],['Propostas contábeis','5','Sem escrituração oficial'],['Aprovações pendentes','4','Inclui 1 bloqueada']];
metrics.forEach(([label,value,note],index)=>{const card=node('article',undefined,'card metric'+(index===2?' attention':''));card.append(node('small',label),node('strong',value),node('footer',note));$('.metrics').append(card);});
function showDetails(record){$('#detail-title').textContent=record.id+' · '+record.name;const content=$('#detail-content');content.replaceChildren();content.append(node('span',states[record.status][1],'badge '+states[record.status][0]));const trail=node('ol');['Origem: documento sintético '+record.id,'Regra: '+record.rule,'Proposta: '+record.proposal,'Responsável: '+record.owner].forEach(step=>trail.append(node('li',step)));content.append(trail,node('p',record.status==='approved'?'Exemplo de decisão humana vinculada à revisão. Este registro é fictício.':'Preparação automática não constitui aprovação. O profissional deve conferir a revisão no ambiente autenticado.'),node('div','Dados demonstrativos; regras ilustrativas sem validade contábil. Ações, bloqueios e versões serão revalidados pelo backend.','human-note'));$('#detail').showModal();}
function render(){const query=$('#search').value.toLocaleLowerCase('pt-BR');const status=$('#status').value;const visible=records.filter(record=>(status==='all'||record.status===status)&&(`${record.id} ${record.name} ${record.owner}`.toLocaleLowerCase('pt-BR').includes(query))&&(!['fiscal','financial'].includes(currentModule)||record.type===currentModule)&&(currentModule!=='governance'||record.status==='blocked')&&(currentModule!=='accounting'||record.status!=='processing'));$('#rows').replaceChildren();visible.forEach(record=>{const row=node('tr');const origin=node('td',record.id);origin.append(node('small',record.name));const rule=node('td',record.proposal);rule.append(node('small',record.rule));const state=node('td');state.append(node('span',states[record.status][1],'badge '+states[record.status][0]));if(record.status==='review')state.append(node('small','◇ Sugestão automática'));const action=node('td');const button=node('button','Ver revisão →');button.type='button';button.setAttribute('aria-label','Ver revisão '+record.id);button.addEventListener('click',()=>showDetails(record));action.append(button);row.append(origin,rule,state,node('td',record.owner),action);$('#rows').append(row);});if(!visible.length){const cell=node('td','Nenhum documento encontrado. Ajuste os filtros.');cell.colSpan=5;const row=node('tr');row.append(cell);$('#rows').append(row);}$('#result-count').textContent=`${visible.length} de ${records.length} registros sintéticos · Histórico ilustrativo`;}
$('#search').addEventListener('input',render);$('#status').addEventListener('change',render);
document.querySelectorAll('[data-module]').forEach(button=>button.addEventListener('click',()=>{currentModule=button.dataset.module;document.querySelectorAll('[data-module]').forEach(item=>item.removeAttribute('aria-current'));button.setAttribute('aria-current','page');$('#page-title').textContent=modules[currentModule][0];$('#module-description').textContent=modules[currentModule][1];$('#search').value='';$('#status').value='all';render();}));
$('#receive').addEventListener('click',()=>$('#upload').showModal());$('#show-lock').addEventListener('click',()=>showDetails(records.find(record=>record.status==='blocked')));
document.querySelectorAll('dialog').forEach(dialog=>dialog.querySelectorAll('.close,.close-detail').forEach(button=>button.addEventListener('click',()=>dialog.close())));
render();
