from typing import Protocol
from uuid import UUID

from serdial21.modules.banking.domain.entities import BankAccount, BankStatement, BankTransaction


class BankingRepository(Protocol):
    def find_account(self, tenant_id: UUID, company_id: UUID, external_identity: str) -> BankAccount | None: ...
    def add_account(self, account: BankAccount) -> None: ...
    def find_statement_by_artifact(self, tenant_id: UUID, company_id: UUID, bank_account_id: UUID, artifact_id: UUID) -> BankStatement | None: ...
    def add_statement(self, statement: BankStatement) -> None: ...
    def find_transaction_by_fitid(self, tenant_id: UUID, company_id: UUID, bank_account_id: UUID, fitid: str) -> BankTransaction | None: ...
    def find_transaction_by_fingerprint(self, tenant_id: UUID, company_id: UUID, bank_account_id: UUID, fingerprint: str) -> BankTransaction | None: ...
    def add_transaction(self, transaction: BankTransaction) -> None: ...
