from typing import Protocol
from uuid import UUID

from serdial21.modules.locks.domain.entities import AccountLock


class AccountLockRepository(Protocol):
    def add(self, lock: AccountLock) -> None: ...
    def get(self, tenant_id: UUID, lock_id: UUID) -> AccountLock | None: ...
    def list_active(self, tenant_id: UUID, company_id: UUID) -> tuple[AccountLock, ...]: ...
    def save(self, lock: AccountLock) -> None: ...
