'''Modelos ORM imut\u00e1veis das sa\u00eddas banc\u00e1rias can\u00f4nicas.''' 
from datetime import date, datetime
from decimal import Decimal
from uuid import UUID, uuid4
from sqlalchemy import ForeignKeyConstraint, Index, Numeric, String, UniqueConstraint, Uuid, event, func
from sqlalchemy.orm import Mapped, mapped_column
from serdial21.bootstrap.database import Base, UTCDateTime

TABLE_OPTIONS = {'mysql_charset': 'utf8mb4', 'mysql_collate': 'utf8mb4_unicode_ci'}
class ImmutableBankingRecordError(RuntimeError): pass
class BankAccountModel(Base):
    __tablename__='bank_accounts'; __table_args__=(UniqueConstraint('tenant_id','company_id','external_identity',name='uq_bank_accounts_scope_identity'),UniqueConstraint('tenant_id','company_id','id',name='uq_bank_accounts_scope_id'),ForeignKeyConstraint(['tenant_id','company_id'],['companies.tenant_id','companies.id'],name='fk_bank_accounts_scope_company'),TABLE_OPTIONS)
    id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4); tenant_id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),nullable=False); company_id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),nullable=False)
    bank_id: Mapped[str|None]=mapped_column(String(40)); branch_id: Mapped[str|None]=mapped_column(String(40)); account_number: Mapped[str]=mapped_column(String(100),nullable=False); account_type: Mapped[str|None]=mapped_column(String(30)); currency_code: Mapped[str|None]=mapped_column(String(10)); external_identity: Mapped[str]=mapped_column(String(255),nullable=False); created_at: Mapped[datetime]=mapped_column(UTCDateTime(),nullable=False,server_default=func.current_timestamp())
class BankStatementModel(Base):
    __tablename__='bank_statements'; __table_args__=(UniqueConstraint('tenant_id','company_id','id',name='uq_bank_statements_scope_id'),UniqueConstraint('tenant_id','company_id','bank_account_id','artifact_id',name='uq_bank_statements_scope_account_artifact'),ForeignKeyConstraint(['tenant_id','company_id','bank_account_id'],['bank_accounts.tenant_id','bank_accounts.company_id','bank_accounts.id'],name='fk_bank_statements_scope_account'),ForeignKeyConstraint(['tenant_id','artifact_id'],['evidence_artifacts.tenant_id','evidence_artifacts.id'],name='fk_bank_statements_tenant_artifact'),ForeignKeyConstraint(['tenant_id','company_id','artifact_id','transformation_run_id'],['transformation_runs.tenant_id','transformation_runs.company_id','transformation_runs.artifact_id','transformation_runs.id'],name='fk_bank_statements_scope_run'),TABLE_OPTIONS)
    id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4); tenant_id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),nullable=False); company_id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),nullable=False); bank_account_id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),nullable=False); artifact_id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),nullable=False); transformation_run_id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),nullable=False); schema_version: Mapped[str]=mapped_column(String(30),nullable=False); start_date: Mapped[date|None]=mapped_column(); end_date: Mapped[date|None]=mapped_column(); opening_balance: Mapped[Decimal|None]=mapped_column(Numeric(20,2)); closing_balance: Mapped[Decimal|None]=mapped_column(Numeric(20,2)); currency_code: Mapped[str|None]=mapped_column(String(10)); sign_policy: Mapped[str]=mapped_column(String(80),nullable=False); source_hash: Mapped[str]=mapped_column(String(64),nullable=False); fingerprint: Mapped[str]=mapped_column(String(64),nullable=False); created_at: Mapped[datetime]=mapped_column(UTCDateTime(),nullable=False,server_default=func.current_timestamp())
class BankTransactionModel(Base):
    __tablename__='bank_transactions'; __table_args__=(UniqueConstraint('tenant_id','company_id','id',name='uq_bank_transactions_scope_id'),UniqueConstraint('tenant_id','company_id','bank_account_id','fitid',name='uq_bank_transactions_scope_fitid'),UniqueConstraint('tenant_id','company_id','bank_account_id','fingerprint',name='uq_bank_transactions_scope_fingerprint'),ForeignKeyConstraint(['tenant_id','company_id','bank_statement_id'],['bank_statements.tenant_id','bank_statements.company_id','bank_statements.id'],name='fk_bank_transactions_scope_statement'),ForeignKeyConstraint(['tenant_id','company_id','bank_account_id'],['bank_accounts.tenant_id','bank_accounts.company_id','bank_accounts.id'],name='fk_bank_transactions_scope_account'),Index('ix_bank_transactions_scope_posted_date','tenant_id','company_id','posted_date'),TABLE_OPTIONS)
    id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),primary_key=True,default=uuid4); tenant_id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),nullable=False); company_id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),nullable=False); bank_statement_id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),nullable=False); bank_account_id: Mapped[UUID]=mapped_column(Uuid(as_uuid=True),nullable=False); fitid: Mapped[str|None]=mapped_column(String(255)); external_reference: Mapped[str|None]=mapped_column(String(255)); transaction_date: Mapped[date|None]=mapped_column(); posted_date: Mapped[date|None]=mapped_column(); amount: Mapped[Decimal]=mapped_column(Numeric(20,2),nullable=False); direction: Mapped[str]=mapped_column(String(10),nullable=False); description: Mapped[str|None]=mapped_column(String(1000)); document_number: Mapped[str|None]=mapped_column(String(255)); fingerprint: Mapped[str]=mapped_column(String(64),nullable=False); identity_kind: Mapped[str]=mapped_column(String(20),nullable=False); created_at: Mapped[datetime]=mapped_column(UTCDateTime(),nullable=False,server_default=func.current_timestamp())
def _prevent_change(*_: object) -> None: raise ImmutableBankingRecordError('registro banc\u00e1rio derivado \u00e9 imut\u00e1vel')
for _model in (BankAccountModel,BankStatementModel,BankTransactionModel): event.listen(_model,'before_update',_prevent_change); event.listen(_model,'before_delete',_prevent_change)
